---
namespace: delinea
name: core
version: 1.0.0
readme: README.md
authors:
  - Delinea (https://delinea.com/)
description: Delinea Collection for Ansible.
license:
  - GPL-3.0-or-later
tags:
  - delinea
  - dsv
  - vault
  - cloud
  - application
  - security
  - secret
  - secrets
  - password
  - passwords
repository: https://github.com/DelineaXPM/ansible-core-collection
documentation: https://github.com/DelineaXPM/ansible-core-collection
homepage: https://github.com/DelineaXPM/ansible-core-collection
issues: https://github.com/DelineaXPM/ansible-core-collection/issues
build_ignore:
  # Directories:
  - .cache
  - .devcontainer
  - .github
  - .trunk
  - .vscode
  - .venv
  - changelogs
  - venv
  - vendor
  # Files:
  - .changie.yaml
  - .editorconfig
  - .flake8
  - .gitattributes
  - .github
  - .gitignore
  - .gitleaks.toml
  - .golangci.yml
  - .markdownlint.yaml
  - .pre-commit-config.yaml
  - .whitesource
  - .yamllint.yaml
  - aqua.yaml
  - CHANGELOG.rst
  - codecov.yml
  - DEVELOPER.md
  - go.mod
  - go.sum
  - magefile.go
  - renovate.json
