---
namespace: delinea
name: core
version: 1.0.0
readme: README.md
authors:
  - Delinea (https://delinea.com/)
description: Delinea Collection for Ansible.
license:
  - GPL-3.0-or-later
tags: [delinea, dsv]

repository: https://github.com/DelineaXPM/ansible-core-collection
documentation: https://github.com/DelineaXPM/ansible-core-collection
homepage: https://github.com/DelineaXPM/ansible-core-collection
issues: https://github.com/DelineaXPM/ansible-core-collection/issues

build_ignore:
  - .flake8
  - .gitattributes
  - .github
  - .gitignore
  - .gitleaks.toml
  - .markdownlint-cli2.yaml
  - .pre-commit-config.yaml
  - .yamllint.yaml
  - go.mod
  - go.sum
  - magefile.go
