---
name: release

on:
  workflow_dispatch:

env:
  ANSIBLE: "stable-2.13"
  HERE: "./ansible_collections/delinea/core"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Pull
        uses: actions/checkout@v3
        with:
          path: ${{ env.HERE }}

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Aqua
        uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        continue-on-error: true
        with:
          aqua_version: v1.32.0
          enable_aqua_install: true
          aqua_opts: "--tags release"
          working_directory: ${{ env.HERE }}

      - name: Init
        run: mage initCI ${{ env.ANSIBLE }}
        working-directory: ${{ env.HERE }}

      - name: Env
        run: mage doctor
        working-directory: ${{ env.HERE }}

      - name: Sanity
        run: mage testSanity
        working-directory: ${{ env.HERE }}

      - name: Build
        run: mage build
        working-directory: ${{ env.HERE }}

      - name: Publish
        run: mage publish
        working-directory: ${{ env.HERE }}
        env:
          GALAXY_SERVER: "https://galaxy.ansible.com/"
          #GALAXY_KEY: ""
