---
name: test

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  HERE: "./ansible_collections/delinea/core"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    name: ansible-${{ matrix.ansible }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        ansible:
          - stable-2.10
          - stable-2.11
          - stable-2.12
          - stable-2.13
          - devel

    steps:
      - name: Pull
        uses: actions/checkout@v3
        with:
          path: ${{ env.HERE }}

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Aqua
        uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # tag=v1.2.0
        continue-on-error: true
        with:
          aqua_version: v1.32.0
          enable_aqua_install: true
          aqua_opts: "--tags tests"
          working_directory: ${{ env.HERE }}

      - name: Init
        run: mage initCI ${{ matrix.ansible }}
        working-directory: ${{ env.HERE }}

      - name: Unit
        run: mage testUnit
        working-directory: ${{ env.HERE }}

      - name: Sanity
        run: mage testSanity
        working-directory: ${{ env.HERE }}

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
